### ISSUE TITLE
Validate Address

### ISSUE THREAD

**Issue by argz7** [sublimator/ripple-lib-java#20]
Hi, I know this is kind of a stupid question.

But how do I check a string if it is a valid ripple address?

**Comment by sublimator** [comment]
https://github.com/sublimator/ripple-lib-java/blob/master/ripple-core/src/main/java/com/ripple/encodings/addresses/Addresses.java#L74

**Comment by sublimator** [comment]
Yeah, I did a lot of refactoring around xmas times ... it’s much further
ahead of the ripple fork

**Comment by sublimator** [comment]
open an issue with some of the errors, I might be able to look into it at
some point
